name: coverage

on:
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@development
      - name: Generate coverage report
        run: |
          yarn global add nx
          yarn install
          nx coverage ioc
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: .
          files: junit.xml
